baseurl = "http://www.effinger.ch"
languageCode = "de"
title = "Effinger â€” Kaffeebar & Coworking Space Bern"

paginatePath = "seite"

[params]
  author = "Coworking Community Bern"
  analyticsId = "UA-56906982-1"
  disqusShortname = "effinger"

[taxonomies]
  tag = "tags"
  category = "categories"
  
[[menu.main]]
  name = "Community"
  pre = "<i class='fa fa-users'></i>"
  weight = 3
  url = "/community/ueber/"
  
[[menu.main]]
  name = "Events"
  weight = 4
  url = "/events/"
  
[[menu.main]]
  name = "Blog"
  weight = 5
  url = "/blog/"